#!/usr/bin/env zsh

cat << EOF
/**
 * This file contains barrel exports for all non-contrib files in fun.
 * It is generated by the \`./scripts/mod.sh\` file. Please do not edit
 * it manually.
 *
 * @module Exports
 * @since 2.0.0
 */

EOF

for i in *[!(mod)].ts; do echo "export * as ${i:s/\.ts//} from \"./$i\";"; done
