name: Check Format

on: [workflow_call]

jobs:
  format:
    strategy:
      matrix:
        deno: ["v2.2.12"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run Deno Check Formatting
        run: deno fmt --check
